language: go

go:
  - master

install:
  - ./scripts/install-hugo.sh

jobs:
  include:
    # Just generate the website
    - stage: Test Build
      if: branch = "master" AND type = "pull_request"
      script:
        - hugo

    # Build and deploy generated content to the gh-pages branch
    - stage: Staging Deploy
      if: branch = "master" AND type = "push"
      script:
        - hugo -b "$STAGING_SITE_URL"
        - echo "$CNAME_URL" > public/CNAME
      deploy:
        provider: pages
        github-token: "$GITHUB_OAUTH_TOKEN"
        skip-cleanup: true
        email: "$GITHUB_EMAIL"
        name: "$GITHUB_USERNAME"
        verbose: true
        keep-history: true
        local-dir: public
        target-branch: gh-pages
        on:
          branch: master

    # Generate content and attach as tarball to the release
    - stage: GitHub Release
      if: tag IS present
      script: hugo -b $LIVE_SITE_URL && tar -zcvf website-$TRAVIS_TAG.tar.gz public;
      deploy:
        provider: releases
        api_key: "$GITHUB_OAUTH_TOKEN"
        file: website-$TRAVIS_TAG.tar.gz
        skip_cleanup: true
        on:
          tags: true
